import type { AvatarPackage, Rule } from '@naavos/schema';

import type { FileMap } from '../index.js';

/**
 * Cursor adapter — generates .cursorrules with identity, communication
 * style, operating rules, and privacy settings.
 */
export function cursorAdapter(pkg: AvatarPackage): FileMap {
  const identity = pkg.identity ?? {};
  const communication = pkg.communication ?? {};
  const rules = pkg.operating_rules ?? [];

  const content = `# .cursorrules — NAAvOS Integration

> Generated by NAAvOS. Do not edit manually — recompile instead.

## Identity

- **Name:** ${identity.name || 'Unknown'}
- **Roles:** ${(identity.roles || []).join(', ') || 'None'}
- **Description:** ${identity.self_description || 'No description provided.'}

## Communication Style

- **Tone:** ${communication.tone || 'Direct, authoritative, straight-talk'}
- **Structure:** ${communication.structure || 'Bulleted, action-oriented'}
- **Verbosity:** ${communication.verbosity || 'Minimal — no preamble, no fluff'}
- **Accessibility needs:** ${(communication.accessibility_needs || []).join(', ') || 'None specified'}
- **Avoid:** ${(communication.prohibited_patterns || []).join(', ') || 'None specified'}

## Operating Rules

${formatRules(rules)}

## Privacy

- **Cloud sync:** ${fmtBool(pkg.privacy?.consents?.['allow-cloud-sync'])}
- **Telemetry:** ${fmtBool(pkg.privacy?.consents?.['allow-telemetry'])}

---
*Compiled from NAAvOS package ${pkg.metadata?.package_id || 'unknown'} — ${new Date().toISOString()}*
`;

  return new Map([['.cursorrules', content]]);
}

function formatRules(rules: Rule[]): string {
  return rules
    .map((r) => `- **${r.id || r.statement.slice(0, 30)}:** ${r.statement} (priority: ${r.priority})`)
    .join('\n');
}

function fmtBool(value: boolean | undefined): 'Allowed' | 'Disabled' {
  return value ? 'Allowed' : 'Disabled';
}
