import type { AvatarPackage, Rule } from '@naavos/schema';

import type { FileMap } from '../index.js';

/**
 * Hermes adapter — generates the full Hermes runtime file set:
 *   SOUL.md, SKILL.md, sub-agents/*.md (one per mode), memories/MEMORY.md,
 *   profiles/avatar/memories/MEMORY.md (duplicate for Hermes path),
 *   profiles/avatar/memories/USER.md
 */
export function hermesAdapter(pkg: AvatarPackage): FileMap {
  const files = new Map<string, string>();

  files.set('SOUL.md', generateSoul(pkg));
  files.set('SKILL.md', generateSkill(pkg));

  if (pkg.modes && pkg.modes.length > 0) {
    for (const mode of pkg.modes) {
      files.set(`sub-agents/${mode.id}.md`, generateSubAgent(pkg, mode));
    }
  }

  files.set('memories/MEMORY.md', generateMemory(pkg));
  files.set('profiles/avatar/memories/MEMORY.md', generateMemory(pkg));
  files.set('profiles/avatar/memories/USER.md', generateUserMemory(pkg));

  return files;
}

function generateSoul(pkg: AvatarPackage): string {
  const identity = pkg.identity ?? {};
  const communication = pkg.communication ?? {};
  const rules = pkg.operating_rules ?? [];

  return `# ${identity.name || 'Avatar'} — SOUL

> Generated by NAAvOS. Do not edit manually — recompile instead.

## Identity

- **Name:** ${identity.name || 'Unknown'}
- **Roles:** ${(identity.roles || []).join(', ') || 'None'}
- **Description:** ${identity.self_description || 'No description provided.'}

## Communication Style

- **Tone:** ${communication.tone || 'Direct'}
- **Structure:** ${communication.structure || 'Bulleted, action-oriented'}
- **Verbosity:** ${communication.verbosity || 'Minimal'}
- **Avoid:** ${(communication.prohibited_patterns || []).join(', ') || 'None specified'}

## Operating Rules

${formatRulesWithPriority(rules)}

## Privacy

- **Cloud sync:** ${fmtBool(pkg.privacy?.consents?.['allow-cloud-sync'])}
- **Telemetry:** ${fmtBool(pkg.privacy?.consents?.['allow-telemetry'])}
- **Data residency:** ${pkg.privacy?.data_residency || 'Not specified'}
- **Retention:** ${pkg.privacy?.retention_policy || 'Not specified'}

---
*Compiled from NAAvOS package ${pkg.metadata?.package_id || 'unknown'} — ${new Date().toISOString()}*
`;
}

function generateSkill(pkg: AvatarPackage): string {
  const identity = pkg.identity ?? {};
  const rules = pkg.operating_rules ?? [];

  return `# ${identity.name || 'Avatar'} Skill

> Generated by NAAvOS. Drop into ~/.hermes/skills/${identity.name || 'avatar'}/SKILL.md

## When to use this skill

Activate when the user requests avatar-specific behavior, persona alignment, or operating-rule enforcement.

## Instructions

1. Load the canonical SOUL.md from the Hermes home directory.
2. Apply the communication style and operating rules defined there.
3. If a mode overlay exists in sub-agents/, activate it when the user requests that mode.
4. Never reveal raw secrets or private project context unless explicitly authorized by the privacy policy.

## Operating Rules

${formatRules(rules)}

## Related Files

- \`SOUL.md\` — Core identity
- \`sub-agents/*.md\` — Mode overlays
- \`memories/MEMORY.md\` — Persistent memory
`;
}

function generateSubAgent(pkg: AvatarPackage, mode: NonNullable<AvatarPackage['modes']>[number]): string {
  const capabilities = mode.permitted_capabilities || [];
  return `# Mode: ${mode.id}

> Generated by NAAvOS. Drop into ~/.hermes/sub-agents/${mode.id}.md

## Activation

- **Phrases:** ${mode.activation_phrases.join(', ')}
- **Deactivation:** ${mode.deactivation_phrases.join(', ')}
- **Persistence:** ${mode.persistence}

## Conflicts

${mode.conflicts?.length ? 'This mode conflicts with: ' + mode.conflicts.join(', ') : 'None'}

## Permitted Capabilities

${capabilities.length ? capabilities.join('\n') : 'All capabilities permitted'}

---
*Compiled from NAAvOS package ${pkg.metadata?.package_id || 'unknown'}*
`;
}

function generateMemory(pkg: AvatarPackage): string {
  const rules = pkg.operating_rules ?? [];
  const identity = pkg.identity ?? {};
  return `# Memory — ${identity.name || 'Avatar'}

> Generated by NAAvOS. Drop into ~/.hermes/memories/MEMORY.md

## User Identity

- **Name:** ${identity.name || 'Unknown'}
- **Roles:** ${(identity.roles || []).join(', ') || 'None'}

## Operating Rules

${formatRules(rules)}

## Last Updated

${new Date().toISOString()}
`;
}

function generateUserMemory(pkg: AvatarPackage): string {
  const identity = pkg.identity ?? {};
  const communication = pkg.communication ?? {};
  return `# User Memory — ${identity.name || 'Avatar'}

> Generated by NAAvOS. Drop into ~/.hermes/profiles/avatar/memories/USER.md

## Preferences

- **Communication:** ${communication.verbosity || 'Minimal'} / ${communication.tone || 'Direct'}
- **Structure:** ${communication.structure || 'Bulleted, action-oriented'}

## Notes

This file is maintained by the Hermes runtime. Do not edit manually.
`;
}

/**
 * Format rules with priority as a bulleted list: "- **id:** statement (priority: N)"
 * Fixed from original O(n²) rules.indexOf(r) pattern.
 */
function formatRulesWithPriority(rules: Rule[]): string {
  return rules
    .map((r) => `- **${r.id || r.statement.slice(0, 30)}:** ${r.statement} (priority: ${r.priority})`)
    .join('\n');
}

/**
 * Format rules as a bulleted list without priority: "- **id:** statement"
 */
function formatRules(rules: Rule[]): string {
  return rules
    .map((r) => `- **${r.id || r.statement.slice(0, 30)}:** ${r.statement}`)
    .join('\n');
}

function fmtBool(value: boolean | undefined): 'Allowed' | 'Disabled' {
  return value ? 'Allowed' : 'Disabled';
}
