export function remeAdapter(pkg) {
  const identity = pkg.identity || {};
  const knowledgeSources = pkg.knowledge_sources || [];
  const remeSource = knowledgeSources.find(ks => ks.type === 'connector-reme');
  const config = remeSource?.config || {};

  const workspaceDir = config.workspaceDir || '.reme';
  const servicePort = config.servicePort || 2333;
  const enableAutoMemory = config.enableAutoMemory !== false;
  const enableAutoDream = config.enableAutoDream !== false;
  const enableEmbeddings = config.enableEmbeddings || false;

  const files = new Map();

  const remerc = `# ReMe Configuration
# Generated by NAAvOS. Do not edit manually — recompile instead.

workspace_dir: ${workspaceDir}
service:
  port: ${servicePort}

components:
  as_auto_memory: ${enableAutoMemory ? 'true' : 'false'}
  as_auto_dream: ${enableAutoDream ? 'true' : 'false'}
  as_embedding: ${enableEmbeddings ? 'true' : 'false'}
  as_embedding_store: ${enableEmbeddings ? 'default' : ''}

# Memory as File, File as Memory
# Workspace layers: session/ -> daily/ -> digest/
# See: https://reme.agentscope.io/?doc=memory-as-file-en

---
*Compiled from NAAvOS package ${pkg.metadata?.package_id || 'unknown'} — ${new Date().toISOString()}*
`;

  files.set('.remerc', remerc);

  const skillContent = `# ReMe Memory Skill

> Generated by NAAvOS. Drop into ~/.hermes/skills/reme_memory/SKILL.md

## When to use this skill

Activate when the user requests memory search, knowledge recall, conversation history, or long-term context from ReMe.

## Prerequisites

- ReMe is installed: \`pip install "reme-ai[core]"\`
- ReMe service is running: \`reme start\`
- Default service address: \`http://127.0.0.1:2333\`

## Instructions

1. Before answering questions that might benefit from historical context, run:
   \`\`\`bash
   reme search query="<user topic>" limit=5
   \`\`\`
2. Read the returned Markdown memory nodes to incorporate relevant context.
3. After significant conversations or decisions, enqueue:
   \`\`\`bash
   reme write path=session/dialog/<session_id> name="<topic>" content="<summary>"
   \`\`\`
4. Never expose raw secrets or private memory content unless explicitly authorized by the privacy policy.

## Related Files

- \`SOUL.md\` — Core identity and communication rules
- \`.remerc\` — ReMe configuration
- \`memories/MEMORY.md\` — Persistent memory
`;
  files.set('skills/reme_memory/SKILL.md', skillContent);

  const claudeInstructions = `## Memory System (ReMe)

This project uses [ReMe](https://reme.agentscope.io) for local-first, self-evolving memory.

### Configuration

- Workspace: \`${workspaceDir}/\`
- Service port: \`${servicePort}\`
- Auto Memory: ${enableAutoMemory ? 'enabled' : 'disabled'}
- Auto Dream: ${enableAutoDream ? 'enabled' : 'disabled'}
- Embeddings: ${enableEmbeddings ? 'enabled' : 'disabled'}

### Usage

Before answering from memory:
\`\`\`bash
reme search query="<topic>" limit=5
\`\`\`

After important conversations:
\`\`\`bash
reme write path=session/dialog/<session_id> name="<topic>" content="<summary>"
\`\`\`

### Privacy

- Cloud sync: ${pkg.privacy?.consents?.['allow-cloud-sync'] ? 'Allowed' : 'Disabled'}
- Telemetry: ${pkg.privacy?.consents?.['allow-telemetry'] ? 'Allowed' : 'Disabled'}
`;
  files.set('CLAUDE-reme.md', claudeInstructions);

  return files;
}
