import type { AvatarPackage, KnowledgeSource } from '@naavos/schema';

import type { FileMap } from '../index.js';

interface ReMeConfig {
  workspaceDir: string;
  servicePort: number;
  enableAutoMemory: boolean;
  enableAutoDream: boolean;
  enableEmbeddings: boolean;
}

/**
 * ReMe adapter — generates .remerc, skills/reme_memory/SKILL.md,
 * and CLAUDE-reme.md with ReMe-specific memory system configuration.
 */
export function remeAdapter(pkg: AvatarPackage): FileMap {
  const config = extractReMeConfig(pkg);

  const files = new Map<string, string>();

  const remerc = `# ReMe Configuration
# Generated by NAAvOS. Do not edit manually — recompile instead.

workspace_dir: ${config.workspaceDir}
service:
  port: ${config.servicePort}

components:
  as_auto_memory: ${config.enableAutoMemory ? 'true' : 'false'}
  as_auto_dream: ${config.enableAutoDream ? 'true' : 'false'}
  as_embedding: ${config.enableEmbeddings ? 'true' : 'false'}
  as_embedding_store: ${config.enableEmbeddings ? 'default' : ''}

# Memory as File, File as Memory
# Workspace layers: session/ -> daily/ -> digest/
# See: https://reme.agentscope.io/?doc=memory-as-file-en

---
*Compiled from NAAvOS package ${pkg.metadata?.package_id || 'unknown'} — ${new Date().toISOString()}*
`;

  files.set('.remerc', remerc);

  const skillContent = `# ReMe Memory Skill

> Generated by NAAvOS. Drop into ~/.hermes/skills/reme_memory/SKILL.md

## When to use this skill

Activate when the user requests memory search, knowledge recall, conversation history, or long-term context from ReMe.

## Prerequisites

- ReMe is installed: \`pip install "reme-ai[core]"\`
- ReMe service is running: \`reme start\`
- Default service address: \`http://127.0.0.1:${config.servicePort}\`

## Instructions

1. Before answering questions that might benefit from historical context, run:
   \`\`\`bash
   reme search query="<user topic>" limit=5
   \`\`\`
2. Read the returned Markdown memory nodes to incorporate relevant context.
3. After significant conversations or decisions, enqueue:
   \`\`\`bash
   reme write path=session/dialog/<session_id> name="<topic>" content="<summary>"
   \`\`\`
4. Never expose raw secrets or private memory content unless explicitly authorized by the privacy policy.

## Related Files

- \`SOUL.md\` — Core identity and communication rules
- \`.remerc\` — ReMe configuration
- \`memories/MEMORY.md\` — Persistent memory
`;
  files.set('skills/reme_memory/SKILL.md', skillContent);

  const claudeInstructions = `## Memory System (ReMe)

This project uses [ReMe](https://reme.agentscope.io) for local-first, self-evolving memory.

### Configuration

- Workspace: \`${config.workspaceDir}/\`
- Service port: \`${config.servicePort}\`
- Auto Memory: ${config.enableAutoMemory ? 'enabled' : 'disabled'}
- Auto Dream: ${config.enableAutoDream ? 'enabled' : 'disabled'}
- Embeddings: ${config.enableEmbeddings ? 'enabled' : 'disabled'}

### Usage

Before answering from memory:
\`\`\`bash
reme search query="<topic>" limit=5
\`\`\`

After important conversations:
\`\`\`bash
reme write path=session/dialog/<session_id> name="<topic>" content="<summary>"
\`\`\`

### Privacy

- Cloud sync: ${fmtBool(pkg.privacy?.consents?.['allow-cloud-sync'])}
- Telemetry: ${fmtBool(pkg.privacy?.consents?.['allow-telemetry'])}
`;
  files.set('CLAUDE-reme.md', claudeInstructions);

  return files;
}

/**
 * Extract ReMe configuration from the avatar package's knowledge_sources.
 * Knowledge sources can be strings (backward-compatible) or objects
 * with a `type` field and `config` object.
 *
 * Fixed from original code: the schema now properly types knowledge_sources
 * as a union of string | KnowledgeSource, and this function handles the
 * type narrowing correctly instead of relying on duck-typing.
 */
function extractReMeConfig(pkg: AvatarPackage): ReMeConfig {
  const sources = pkg.knowledge_sources ?? [];

  for (const source of sources) {
    if (typeof source === 'object' && source !== null) {
      const ks = source as KnowledgeSource;
      if (ks.type === 'connector-reme' && ks.config) {
        const config = ks.config as Record<string, unknown>;
        return {
          workspaceDir: (config['workspaceDir'] as string) ?? '.reme',
          servicePort: (config['servicePort'] as number) ?? 2333,
          enableAutoMemory: config['enableAutoMemory'] !== false,
          enableAutoDream: config['enableAutoDream'] !== false,
          enableEmbeddings: (config['enableEmbeddings'] as boolean) ?? false,
        };
      }
    }
  }

  return {
    workspaceDir: '.reme',
    servicePort: 2333,
    enableAutoMemory: true,
    enableAutoDream: true,
    enableEmbeddings: false,
  };
}

function fmtBool(value: boolean | undefined): 'Allowed' | 'Disabled' {
  return value ? 'Allowed' : 'Disabled';
}
